### ISSUE TITLE
About the effect of residual layer ?

### ISSUE THREAD

**Issue by lawpdas** [ybsong00/CREST-Release#10]
@ybsong00  @dynamicsong   Can the residual layer really capture the appearance changes ? I think it only contributes to the training of base layer.

**Comment by ybsong00** [comment]
Check ResNet paper for the idea of residual learning.

**Comment by HaojieCoding** [comment]
Thank you for your reply! But the otb results didn't change when the response map of base layer was used directly(residual layer was retained). So I think the residual layer is ineffective.
